// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdznZVoa_jil_C39tALtuFmkREghRlj6Q',
    appId: '1:64210170701:web:98acd0dafeb80b3c95bd04',
    messagingSenderId: '64210170701',
    projectId: 'trail-ecc92',
    authDomain: 'trail-ecc92.firebaseapp.com',
    storageBucket: 'trail-ecc92.firebasestorage.app',
    measurementId: 'G-7R0HZ2967S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlf_gE2VpBmb8p5nPVQg7r7CQnCIy_eg',
    appId: '1:64210170701:android:2f593f7844cd584c95bd04',
    messagingSenderId: '64210170701',
    projectId: 'trail-ecc92',
    storageBucket: 'trail-ecc92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArgjktMwcWToekL3hD7Yh4UmTc6tNMUQA',
    appId: '1:64210170701:ios:0d4596055df6938195bd04',
    messagingSenderId: '64210170701',
    projectId: 'trail-ecc92',
    storageBucket: 'trail-ecc92.firebasestorage.app',
    iosBundleId: 'com.example.trail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArgjktMwcWToekL3hD7Yh4UmTc6tNMUQA',
    appId: '1:64210170701:ios:0d4596055df6938195bd04',
    messagingSenderId: '64210170701',
    projectId: 'trail-ecc92',
    storageBucket: 'trail-ecc92.firebasestorage.app',
    iosBundleId: 'com.example.trail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdznZVoa_jil_C39tALtuFmkREghRlj6Q',
    appId: '1:64210170701:web:c1d84fe0a8f7741995bd04',
    messagingSenderId: '64210170701',
    projectId: 'trail-ecc92',
    authDomain: 'trail-ecc92.firebaseapp.com',
    storageBucket: 'trail-ecc92.firebasestorage.app',
    measurementId: 'G-9018ZZD4ZQ',
  );
}
